name: Build and Deploy Docker to ECR

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply and Destroy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Wait for EC2 to finish
      run: sleep 120

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
